dist: trusty
sudo: required
language: python
# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: 3.6
services: docker

env:
  global:
    # directory containing the project source
    - REPO_DIR=.
    # pip dependencies to _build_ project
    # - BUILD_DEPENDS="..."
    # pip dependencies to _test_ project
    - TEST_DEPENDS="tox"
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - TWINE_USERNAME="anthrotype"
    - secure: sP6f3S56rHggs9uKQHBCZa/f6vxmE3CmWR3cl9KFFRUrSSxLvrJEIkgOo29Sv6HM/pMdyuMUQmuQ+GDE/WyLYmDELItlPT3reWK7pnD6Ta/nO5t27hBfnVvQvO5AQK6L5lfOd+viM7AO0E7Oo/omnoarGAzUOeOEl1JzSYqyDzYvyNcMSBt3TrwRsW/t3a0TDNTiPNJiC+Hk68TLvjyXD79vGU3GYlds7indcs9R6PpVJFppLNxKT+L0+D2tdz+23eS7vMVw6KFbDbshKo9ZCN4HjSKmyXR5OkMMLnZp95u9ncfsA3x5Kq2gjl1kj053ZbLUbOOFIlA5VT7LLWjWvmr0j3F8Y2UerB0agRrQbft5i9Iy1c6e7dyTrhHR2SRTjh1e5pjnYnPDaxuey2KCtEsod0ClMsJwiJmxiVse7SFWbL9lPw2TO6TFjqbosAUmKM6w7vgTxW2sjWQTeanf4UKs/1L8yeEzkITQJCsV/BiiHcuf8xF+IgIRdPSCP2Wuf1BlU1g+qNCceS3DQBXzvXFWCMu6u69IsTQJbk+BMUm9qlYML7Vba2WLU+PT6W+jYuMFbXyy26s00BQYfM2g937ZJua76s4jSvcJiufjyTubl9WT5NNR7qTq9KHhHO5hvRyaBKTL5I6pnuxwrDbcHkpirbRP7N1uIPobuGxdF/E=

matrix:
  fast_finish: true
  exclude:
    # Exclude the default Python 3.6 build
    - python: 3.6
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7

cache: pip

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - build_wheel $REPO_DIR $PLAT

script:
  - install_run $PLAT

after_success:
  # If it's a tagged commit, upload sdist and wheel packages to PyPI.
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "googlefonts/ots-python" ]; then
        pip install --upgrade pip setuptools wheel twine
        pip wheel -w dist -v --no-deps .
        twine upload dist/*.whl
    fi
