language: python
sudo: false

env:
  global:
  - TWINE_USERNAME="anthrotype"
  - secure: sP6f3S56rHggs9uKQHBCZa/f6vxmE3CmWR3cl9KFFRUrSSxLvrJEIkgOo29Sv6HM/pMdyuMUQmuQ+GDE/WyLYmDELItlPT3reWK7pnD6Ta/nO5t27hBfnVvQvO5AQK6L5lfOd+viM7AO0E7Oo/omnoarGAzUOeOEl1JzSYqyDzYvyNcMSBt3TrwRsW/t3a0TDNTiPNJiC+Hk68TLvjyXD79vGU3GYlds7indcs9R6PpVJFppLNxKT+L0+D2tdz+23eS7vMVw6KFbDbshKo9ZCN4HjSKmyXR5OkMMLnZp95u9ncfsA3x5Kq2gjl1kj053ZbLUbOOFIlA5VT7LLWjWvmr0j3F8Y2UerB0agRrQbft5i9Iy1c6e7dyTrhHR2SRTjh1e5pjnYnPDaxuey2KCtEsod0ClMsJwiJmxiVse7SFWbL9lPw2TO6TFjqbosAUmKM6w7vgTxW2sjWQTeanf4UKs/1L8yeEzkITQJCsV/BiiHcuf8xF+IgIRdPSCP2Wuf1BlU1g+qNCceS3DQBXzvXFWCMu6u69IsTQJbk+BMUm9qlYML7Vba2WLU+PT6W+jYuMFbXyy26s00BQYfM2g937ZJua76s4jSvcJiufjyTubl9WT5NNR7qTq9KHhHO5hvRyaBKTL5I6pnuxwrDbcHkpirbRP7N1uIPobuGxdF/E=

matrix:
  include:
  - env: TOXENV=py36
    python: 3.6

install:
  - pip install tox

script: tox

after_success:
  # If it's a tagged commit, upload sdist and wheel packages to PyPI.
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "anthrotype/ots-python" ]; then
        pip install --upgrade pip setuptools wheel twine
        pip wheel -w dist -v --no-deps .
        twine upload dist/*.whl
    fi
